### ISSUE TITLE
Filter adapters on build tree according to environment options

### ISSUE THREAD

**Issue by denneralex** [poteto/ember-metrics#24]
Today all the adapters on metrics-adapters folder are included in the build tree even if on the config there's only one selected, e.g. if on the environment there's only GoogleAnalytics setup Mixpanel and others are included as well on the vendor.js script.
A better approach would be to filter the files on the build process to include only the ones declared on environment + base.js.

This could be done on the treeForAddon hook in the index.js file, excluding from the broccoli tree the adapters that are not on environment, keeping only necessary adapters + base.js. Would be even better if the base.js file was not on the same folder so the filter doesn't have to care about it.

Let me know your thoughts.

**Comment by poteto** [comment]
I like this idea a lot. Would you like to open a PR for it? :)

**Comment by denneralex** [comment]
Sure, I'll open a PR.

**Comment by jasonmit** [comment]
I can take this on, but I have one question. We'll likely need to add support for another key other than walking `config.metricsAdapters` since we'll still want to support the lazy loading scenario.

We can add another property, `config.metricsSupportedAdapters` or add a property to the objects within metricsAdapters, named `isLazy`, that prevents it from being loaded.

Thoughts?
